PREFIX ore: <http://www.openarchives.org/ore/terms/>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX schema: <https://schema.org/>
PREFIX cd: <http://citydata.wu.ac.at/ns#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>

CONSTRUCT {
  ?creator
	rdf:type schema:Person;
	schema:name ?personNL .
}

WHERE {
    ?heritageObject a edm:ProvidedCHO ;
		dcterms:creators ?creator ;
		dc:description ?discription ;
		dc:creator ?person .
		BIND(STRLANG(str(?person), "nl") as ?personNL)
		FILTER(LANG(?discription) = "nl")


}