#PREFIX ore: <http://www.openarchives.org/ore/terms/>
#PREFIX edm: <http://www.europeana.eu/schemas/edm/>
#PREFIX schema: <http://schema.org/>
#PREFIX cd: <http://citydata.wu.ac.at/ns#>
#PREFIX dc: <http://purl.org/dc/elements/1.1/>
#PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
#PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
#PREFIX dcterms: <http://purl.org/dc/terms/>
#
#CONSTRUCT {
#  ?heritageObject
#
#    dcterms:dateCreated ?final_year .
#
#}
#
#WHERE {
#    ?heritageObject dc:date ?year .
#
#    OPTIONAL {
#        ?artwork dc:date ?another_year .
#        Filter (?year != ?another_year)
#        BIND( IF(?year < ?another_year, ?year, ?another_year) AS ?older_year)
#    }
#     BIND (IF (!BOUND(?another_year), ?year, ?older_year) AS ?final_year) ## to get prossible date without range
##     BIND(xsd:integer(?final_year) AS ?yearCreated)
#
#}



PREFIX ore: <http://www.openarchives.org/ore/terms/>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX schema: <http://schema.org/>
PREFIX cd: <http://citydata.wu.ac.at/ns#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>

#Construct {
#  ?artwork dcterms:date ?yearCreated .
#}
#
#where {
#    ?artwork dc:date ?year .
#    optional {
#        ?artwork dc:date ?another_year .
#        Filter (?year != ?another_year)
#        BIND( if(?year < ?another_year, ?year, ?another_year) AS ?older_year)
#    }
#    BIND (IF (!BOUND(?another_year), ?year, ?older_year) AS ?final_year)
#    BIND(xsd:integer(?final_year) AS ?yearCreated)
#
#}




CONSTRUCT {
  ?artwork dcterms:dateCreated ?jaar .
#  ?artwork dcterms:created ?jaar .
}
#select *

  WHERE {
    select ?artwork (min(?year) as ?jaar)
    where {
          ?artwork dc:date ?year .
    }
    group by ?artwork

}