PREFIX ore: <http://www.openarchives.org/ore/terms/>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX schema: <https://schema.org/>
PREFIX cd: <http://citydata.wu.ac.at/ns#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

#<https://www.catharijneconvent.nl/>
#<https://www.mauritshuis.nl/>
#<https://www.stedelijkmuseumschiedam.nl/>
#<https://www.museumbelvedere.nl/>
#<https://www.catharijneconvent.nl/>
#<https://www.museumdefundatie.nl/>
#<https://vanabbemuseum.nl/
#<https://www.rijksakademie.nl/>

## 1 mauritshuis
#CONSTRUCT {
#
#<https://www.mauritshuis.nl/>
#  a schema:Organization ;
#  schema:name "mauritshuis"@nl ;
#  schema:mainEntityOfPage <https://www.mauritshuis.nl/> .
#}
#WHERE {
#
#}


## 2 vanabbemuseum
#CONSTRUCT {
#
#<https://vanabbemuseum.nl/>
#  a schema:Organization ;
#  schema:name "vanabbemuseum"@nl ;
#  schema:mainEntityOfPage <https://vanabbemuseum.nl/> .
#}
#WHERE {
#
#}

## 3 stedelijkmuseumschiedam
#CONSTRUCT {
#
#<https://www.stedelijkmuseumschiedam.nl/>
#  a schema:Organization ;
#  schema:name "stedelijkmuseumschiedam"@nl ;
#  schema:mainEntityOfPage <https://www.stedelijkmuseumschiedam.nl/> .
#}
#WHERE {
#
#}




# 4 museumdefundatie
#CONSTRUCT {
#
#<https://www.museumdefundatie.nl/>
#  a schema:Organization ;
#  schema:name "museumdefundatie"@nl ;
#  schema:mainEntityOfPage <https://www.museumdefundatie.nl/> .
#}
#WHERE {
#
#}

# 5 rijksakademie
CONSTRUCT {

<https://www.rijksakademie.nl/>
  a schema:Organization ;
  schema:name "rijksakademie"@nl ;
  schema:mainEntityOfPage <https://www.rijksakademie.nl/> .
}
WHERE {

}

## 6 catharijneconvent
#CONSTRUCT {
#
#<https://www.catharijneconvent.nl/>
#  a schema:Organization ;
#  schema:name "catharijneconvent"@nl ;
#  schema:mainEntityOfPage <https://www.catharijneconvent.nl/>.
#}
#WHERE {
#
#}

## 7 museumbelvedere
#CONSTRUCT {
#
#<https://www.museumbelvedere.nl/>
#  a schema:Organization ;
#  schema:name "museumbelvedere"@nl ;
#  schema:mainEntityOfPage <https://www.museumbelvedere.nl/>.
#}
#WHERE {
#
#}






